name: Release

on:
  workflow_dispatch:   # 手动触发

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true

      - name: Update mihomo to Pre-Alpha
        run: |
          go get github.com/metacubex/mihomo@Prerelease-Alpha
          go mod tidy

      - name: Run GoReleaser (Snapshot)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
